In [1]:
import pandas as pd

In [2]:
url = "data/nhanes_2015_2016.csv"
da = pd.read_csv(url)

In [3]:
da.columns

Index(['SEQN', 'ALQ101', 'ALQ110', 'ALQ130', 'SMQ020', 'RIAGENDR', 'RIDAGEYR',
       'RIDRETH1', 'DMDCITZN', 'DMDEDUC2', 'DMDMARTL', 'DMDHHSIZ', 'WTINT2YR',
       'SDMVPSU', 'SDMVSTRA', 'INDFMPIR', 'BPXSY1', 'BPXDI1', 'BPXSY2',
       'BPXDI2', 'BMXWT', 'BMXHT', 'BMXBMI', 'BMXLEG', 'BMXARML', 'BMXARMC',
       'BMXWAIST', 'HIQ210'],
      dtype='object')

In [6]:
da["BMXWT"]

0        94.8
1        90.4
2        83.4
3       109.8
4        55.2
        ...  
5730     59.1
5731    112.1
5732     71.7
5733     78.2
5734     58.3
Name: BMXWT, Length: 5735, dtype: float64

In [7]:
da["BMXWT"].mean()

np.float64(81.34267560889516)

In [8]:
da["DMDEDUC2"]

0       5.0
1       3.0
2       3.0
3       5.0
4       4.0
       ... 
5730    3.0
5731    5.0
5732    4.0
5733    1.0
5734    5.0
Name: DMDEDUC2, Length: 5735, dtype: float64

 Demographics on education: https://wwwn.cdc.gov/Nchs/Nhanes/2015_2016/SMQ_I.htm

In [10]:
da["DMDEDUC2"].unique() # Categorical Ordered

array([ 5.,  3.,  4.,  2., nan,  1.,  9.])

In [12]:
g = da["RIAGENDR"] # Categorical Unordered
g

0       1
1       1
2       1
3       2
4       2
       ..
5730    2
5731    1
5732    2
5733    1
5734    2
Name: RIAGENDR, Length: 5735, dtype: int64

In [13]:
g.unique()

array([1, 2])

# One Hot Encoding

In [14]:
B = ["bird","cat","dog","cat","bird","bird"]

d = {'categorical' : B}
df = pd.DataFrame(d)

In [15]:
df

categorical
0        bird
1         cat
2         dog
3         cat
4        bird
5        bird

In [16]:
df['categorical']

0    bird
1     cat
2     dog
3     cat
4    bird
5    bird
Name: categorical, dtype: object

In [24]:
# "dummies" is used to create columns corresponding to unique values
dfDummies = pd.get_dummies(df['categorical'],prefix = 'category')

In [25]:
dfDummies

category_bird  category_cat  category_dog
0           True         False         False
1          False          True         False
2          False         False          True
3          False          True         False
4           True         False         False
5           True         False         False

In [26]:
dfDummies.values

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False]])